### PR TITLE
Externalized WorkspaceSelector

### PR DESCRIPTION
**Pull request by Defeatomizer**
Hello there, @LoicMaitreDuFeu!

### CODE REVIEW

**Comment by KlemenDEV** [comment]
@Defeatomizer open PR to MCreator instead so loic's PR is separate from yours

**Comment by Defeatomizer** [comment]
I wanted to collaborate so [it](https://github.com/MCreator/MCreator/pull/1459) would be likely the last externalization PR.
But it's not hard for me to reopen it there :D

**Comment by KlemenDEV** [comment]
It is easier for me to check smaller PRs and communicate needed changes to separate authors

**Comment by LoicMaitreDuFeu** [comment]
Lol

**Pull request closed without merging**
